export const ADD_DATA = "ADD_DATA"
export const FAILED_ADD_DATA = "FAILED_ADD_DATA"

export const GET_DATA = "GET_DATA"
export const FAILED_GET_DATA = "FAILED_GET_DATA"

export const UPDATE_DATA = "UPDATE_DATA"
export const FAILED_UPDATE_DATA = "FAILED_UPDATE_DATA"

export const DELETE_DATA = "DELETE_DATA"
export const FAILED_DELETE_DATA = "FAILED_DELETE_DATA"

export const GET_DETAIL_DATA = "GET_DETAIL_DATA"
export const FAILED_GET_DETAIL_DATA = "FAILED_GET_DETAIL_DATA"

export const SEARCH_NAME_DATA = "SEARCH_NAME_DATA"
export const FAILED_SEARCH_NAME_DATA = "FAILED_SEARCH_NAME_DATA"

export const FILTER_STATUS_DATA = "FILTER_STATUS_DATA"
export const FAILED_FILTER_STATUS_DATA = "FAILED_FILTER_STATUS_DATA"